version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: ayahhamdi/reverseproxy
  backend_user:
    build:
      context: ../../backend_user-api
    image: ayahhamdi/udagram-user-api
  backend_feed:
    build:
      context: ../../backend_feed-api
    image: ayahhamdi/udagram-feed-api
  frontend:
    build:
      context: ../../frontend
    image: ayahhamdi/udagram-frontend:local
